version: '3.1'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: transactionsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data